import "@/app/globals.css";
import MainContainer from "@/components/layout/MainContainer";
import TQProvider from "@/components/providers/TQProvider";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

export const metadata: Metadata = {
  //TODO: 타이틀 수정
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      <body>
        <TQProvider>
          <MainContainer>{children}</MainContainer>
        </TQProvider>
      </body>
    </html>
  );
};

export default RootLayout;
